### ISSUE TITLE
SignalR stopped working on 1.0.674 release

### ISSUE THREAD

**Issue by WayneBBB** [MicrosoftEdge/WebView2Feedback#569]
I updated to WebView2 1.0.674-prerelease this morning and installed the latest Edge.Canary (I had Edge.Dev installed but it was incompatible with updates).
For some reason SignalR has stopped working correctly, but was working well yesterday.  The client will send one message and then close.  I have not been able to resolve.

This is what I see in the Edge Developer Console: (chat.js is client and commhubcontrol is hub )

Utils.ts:174 [2020-10-22T16:45:38.945Z] Information: Normalizing '/commhubcontrol' to 'http://192.168.1.10:5000/commhubcontrol'.
Utils.ts:174 [2020-10-22T16:45:39.213Z] Information: WebSocket connected to ws://192.168.1.10:5000/commhubcontrol?id=faDp7KaZVyDl0Bxid8pDEQ.
chat.js:47 Initialize pipe message sent: 
Utils.ts:174 [2020-10-22T16:45:39.366Z] Information: Connection disconnected.
chat.js:48 Error: Invocation canceled due to the underlying connection being closed.
    at HubConnection.connectionClosed (HubConnection.ts:664)
    at HttpConnection.HubConnection.connection.onclose (HubConnection.ts:103)
    at HttpConnection.stopConnection (HttpConnection.ts:498)
    at WebSocketTransport.transport.onclose (HttpConnection.ts:413)
    at WebSocketTransport.close (WebSocketTransport.ts:154)
    at WebSocket.webSocket.onclose (WebSocketTransport.ts:102)
____

The first message is sent to the the Server and received by the Server, which then executes the message successfully (Invoked). Then client then immediately disconnects (I believe).  Not sure what to do from here.  Not sure if this is a Edge problem or SignalR problem.

This is how I have client set up (I've taken out repeative stuff):
________________

var connection = new signalR.HubConnectionBuilder()
    .withUrl("/commhubcontrol")
    .build();

connection.keepAliveIntervalInMilliseconds = 20000;
 
document.getElementById("JRButton").disabled = true;

connection.on("ReceiveMessage", function (user, message) {
    var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    var encodedMsg = user + " says " + msg;
    var li = document.createElement("li");
    console.log(encodedMsg);
    //li.textContent = encodedMsg;

    //document.getElementById("messagesList").appendChild(li);
});

connection.logging = true;

connection.start().then(function () {    
    document.getElementById("JRButton").disabled = false;
    console.log("Initialize pipe message sent: ");
    connection.invoke("Initialize", "MouseHelper", "SetUp").catch(err => console.error(err));

}).catch(function (err) {
    return console.error(err.toString());
});

document.getElementById("JRButton").addEventListener("click", function (event) {
    console.log("Sending JRButton push to PiecesOfPipe");
    var user = document.getElementById("userInput").value;    
    var message = document.getElementById("messageInput").value;
    if (connection.state.isNullOrUndefined())
    {
       connection.start();
    }
    connection.invoke("SendMessage", user, message).catch(function (err) {
        return console.error(err.toString());
    });
    event.preventDefault();
});
______________
The Hub is:

public class CommHubControl :Hub
    {
        private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();
        private readonly IPiecesOfPipe _piecesOfPipe;
       private readonly IMouseActions _mouseActions;

        public CommHubControl(IPiecesOfPipe PiecesOfPipe,IMouseActions mouseActions)
        {
            _piecesOfPipe = PiecesOfPipe;
            _mouseActions = mouseActions;
        }

 public async Task SendMessage(string user, string message)
        {
            Logger.Debug("SendPipeMessage is: " + message );
            var Tresult = await Task.Run(() => _piecesOfPipe.SendPipeMessage(message ));            
        }
public async Task Initialize(string user, string message)
        {
            Logger.Debug("Initialize cmd is: " + message);
            var Result = await Task.Run(() => _mouseActions.StartStopWatch());
            Logger.Debug("Initialize of StopWatch returned: " + Result.ToString());
        }
__________
Startup Class

 public void ConfigureServices(IServiceCollection services)
        {
	    services.Configure<KestrelServerOptions>(
            Configuration.GetSection("Kestrel"));
            services.AddControllersWithViews();
            services.AddSignalR();
            services.AddSingleton<IPiecesOfPipe, PiecesOfPipe>();
            services.AddTransient<IMouseActions, MouseActions>();)
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseStaticFiles();
            app.UseMiddleware<AdminSafeListMiddleware>(Configuration["AdminSafeList"]);
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapHub<CommHubControl>("/commhubcontrol");
 }

**Comment by WayneBBB** [comment]
I have isolated the issue to SignalR, specifically.  Not a WebView2 issue.
