### ISSUE TITLE
0.17.1pre5 does not compile on Unity 2020.3.48f1

### ISSUE THREAD

**Issue by RubenGarcia** [MicrosoftEdge/WebView2Feedback#3726]
**Description**
After installing 0.17.1pre5 on a unity project and opening it with Unity 2020.3.48f1, Unity indicates there are compilation errors and shows these two lines:
```
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,70): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,71): error CS1526: A new expression requires (), [], or {} after type
```
Version 0.17.1pre3 compiles and runs correctly.

**Version**
SDK: 0.17.1pre5
Runtime:  Unknown, how do I find this information?
Framework:  Unknown, how do I find this information?
OS: Windows 10 Enterprise

**Regression**
Was this working before but has regressed? Yes
If yes, what version did this last work on?  0.17.1pre3

**Repro Steps**
Create a Unity project on unity 2020.3.48f1
Use Mixed Reality Feature Tool to install 0.17.1pre5
Open Unity

Expected behaviour:
Everything compiles and runs fine
Actual behaviour: compilation errors mentioned above

**Screenshots**

**Additional context**

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to dev who can help follow up on this.

**Comment by michaelfarnsworth** [comment]
@RubenGarcia technically, we don't support Unity 2020, as it's gone out of LTS. The issue you're running into is likely due to Unity 2020 using C# 8.0, which doesn't support ([target-typed new expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new)
.). Could you try Unity 2021?

**Comment by RubenGarcia** [comment]
Unity 2021 works. I'll close this ticket then.

**Comment by RubenGarcia** [comment]
Since there are only two affected lines, could you make an exception and support Unity 2020 by just fixing these two lines?
If the effort is too high, you may close this ticket.
